### ISSUE TITLE
cp: cannot stat '/tmp/mkmod.YB8nNsPH/build/libs': No such file or directory

### ISSUE THREAD

**Issue by Tank-Missile** [PearXTeam/mkmod#1]
This error occurs after building the ServerSync mod from https://github.com/superzanti/ServerSync.git. I haven't encountered this error when building other mods so far.

**Comment by mrapplexz** [comment]
Looks like ServerSync publishes its build artifacts to another directory. Sorry, I'm busy at the moment. When I'm free, I will update mkmod, so it will support customizing the artifacts directory.

**Comment by Tank-Missile** [comment]
No problem! This script will come in handy for testing mods.

**Comment by mrapplexz** [comment]
Added in 1.3.0. You should add the `-a publish` arguments to build the ServerSync.
